version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jooby_postgres
    restart: always
    environment:
      POSTGRES_USER: jooby_user
      POSTGRES_PASSWORD: jooby_pass
      POSTGRES_DB: jooby_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
