version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: jooby_postgres
    restart: always
    environment:
      POSTGRES_DB: jooby_db
      POSTGRES_USER: jooby_user
      POSTGRES_PASSWORD: jooby_pass
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jooby_user -d jooby_db"]
      interval: 10s
      retries: 5
      start_period: 5s

  app:
    build: .
    container_name: jooby_app
    depends_on:
      postgres:
        condition: service_healthy  # Ждём, пока БД будет полностью готова
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: jooby_user
      DB_PASSWORD: jooby_pass
      DB_NAME: jooby_db
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go"]

volumes:
  postgres_data:
